services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=local
      - POSTGRESQL_PASSWORD=local
      - POSTGRESQL_DATABASE=local
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    networks:
      - api_net
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql

  db_replica:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5433:5432"
    depends_on:
      - db
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=local
      - POSTGRESQL_PASSWORD=local
      - POSTGRESQL_DATABASE=local
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    networks:
      - api_net
    volumes:
      - db_data_replica:/bitnami/postgresql

networks:
  api_net:
    name: api_net
    driver: bridge

volumes:
  db_data:
  db_data_replica:
